project:
  type: book
  execute-dir: project
  output-dir: docs
  
#execute: 
#  freeze: auto

format:
  html:
    theme:
      - lumen
      - custom.scss
    grid: 
      sidebar-width: 275px
    fontsize: "100%"
    # template-partials:
    #   - toc.html
    toc-title: "On this page"
    html-table-processing: none
  # pdf:
  #  documentclass: scrreprt
  #  mainfont: "Open Sans"
  #  fig-pos: "H"
  #  toc-depth: 2
  #  include-in-header:
  #    text: |
  #      \usepackage{float}
  #      \raggedbottom
  #docx: 
  #  toc: true
  #  toc-depth: 1
  #  number-sections: true
  #  fig-align: left
  #  prefer-html: true

book:
  title: "Faith-Based Property Ownership in Virginia"
  repo-url: https://github.com/housingforwardva/yigby
  author: 
    name: "HousingForward Virginia"
    url: https://www.housingforwardva.org
  sidebar: 
    logo: "img/vif_hfv.png"
    search: true
  # downloads: pdf 
  date: today
  chapters:
    - index.qmd 
    - intro.qmd # Introduction
    - methods.qmd # Methods
    - part: "Findings"
      chapters:
        - findings-summary.qmd # Summary findings
        - findings-pdc.qmd # Findings by PDC
        - findings-ga.qmd # Findings by GA district
        - findings-nova.qmd # NOVA zoning analysis
    - conclusions.qmd # Conclusions

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
# comments: 
#   hypothesis: true